# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adbf792dc3e18d7be971567857ee1efa5ccb4e56b5fe782ed2c896f9b048f7d8d86a6883abed93b184923f944dcb5e28148fe64a56d1cff33387e0a2ec9608b1

test:
  secret_key_base: 50e162a3fb8e2cbe7b6193103e17ab78f51cce15ca61083249d74b32e5e7ab9325db00eea9660b82c025c488163ecc5ceecd0adb0594d95ca1d3e407fcef3f57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
